<Workspace Version="1.3.3.4111" X="190.393623924876" Y="12.1686671142517" zoom="0.982642311367965" ScaleFactor="1" Name="Home" Description="" RunType="Automatic" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <DSRevitNodesUI.ElementsOfCategory guid="0e67a3ec-4f12-4d52-a470-e12b048e7ab9" type="DSRevitNodesUI.ElementsOfCategory" nickname="All Elements of Category" x="221.173801346933" y="360.243532682551" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </DSRevitNodesUI.ElementsOfCategory>
    <DSRevitNodesUI.Categories guid="3b313f48-7bde-4568-9e41-f2608b2128b9" type="DSRevitNodesUI.Categories" nickname="Categories" x="8.17380134693303" y="345.243532682551" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="525:Walls" />
    <PythonNodeModels.PythonNode guid="d5e3da1d-e5da-4aeb-a9b0-13ea42662515" type="PythonNodeModels.PythonNode" nickname="Python Script" x="425.5" y="472" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import sys
import clr
# import Revit API
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
# import Revit API UI
clr.AddReference('RevitAPIUI')
# import Revit Services
clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager 
# import ProtoGeometry 
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
# get the current Revit Document 
doc = DocumentManager.Instance.CurrentDBDocument
# get the current Revit application
app = DocumentManager.Instance.CurrentUIApplication.Application
# get the current UI application
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application


list_wall = UnwrapElement(IN[0])
list1 = []

for wall in list_wall:
	a = wall.Id
	list1.append(wall)

OUT = list1</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="126ac364-e0c5-4657-a165-212e5b7e4ab9" type="PythonNodeModels.PythonNode" nickname="Python Script" x="444.5" y="362" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import sys
import clr
# import Revit API
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
# import Revit API UI
clr.AddReference('RevitAPIUI')
# import Revit Services
clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager 
# import ProtoGeometry 
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
# get the current Revit Document 
doc = DocumentManager.Instance.CurrentDBDocument
# get the current Revit application
app = DocumentManager.Instance.CurrentUIApplication.Application
# get the current UI application
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application


list_wall = UnwrapElement(IN[0])
list1 = []

for wall in list_wall:
	typeId = wall.GetTypeId()
	type = doc.GetElement(typeId)
	list1.append(type)

OUT = list1</Script>
    </PythonNodeModels.PythonNode>
    <CoreNodeModels.CreateList guid="c04241fd-0d2e-4d61-85c9-a426e5d1c012" type="CoreNodeModels.CreateList" nickname="List.Create" x="676.5" y="419" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </CoreNodeModels.CreateList>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="39b5c3b3-53a3-4c3d-8bd4-30afe68f9869" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.Transpose" x="838.841554459682" y="449.51288596522" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.List.Transpose@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="04a87303-3483-492c-bac1-288a44c7a0a5" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Excel.WriteToFile" x="1002.37314138805" y="112.654641507592" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSOffice.dll" function="DSOffice.Excel.WriteToFile@string,string,int,int,var[][],bool">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <PortInfo index="3" default="False" />
      <PortInfo index="4" default="False" />
      <PortInfo index="5" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <CoreNodeModels.Input.Filename guid="4e439874-42ab-4efc-abdc-8c7293410eeb" type="CoreNodeModels.Input.Filename" nickname="File Path" x="669.59691527097" y="93.3190198065997" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.String>C:\Users\andre\Desktop\Проект\list_excel</System.String>
      <HintPath>C:\Users\andre\Desktop\Проект\list_excel</HintPath>
    </CoreNodeModels.Input.Filename>
    <CoreNodeModels.Input.StringInput guid="00075c90-1128-4aa8-8c87-26153ad148a2" type="CoreNodeModels.Input.StringInput" nickname="String" x="759.151373675567" y="201.191435612138" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.String>Таблица</System.String>
      <System.String value="Таблица" />
    </CoreNodeModels.Input.StringInput>
    <CoreNodeModels.Input.DoubleInput guid="895bdde7-9fea-45f6-8f13-9003d75935e3" type="CoreNodeModels.Input.DoubleInput" nickname="Number" x="777.469331076508" y="273.445600915847" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.Double value="0" />
    </CoreNodeModels.Input.DoubleInput>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="0e67a3ec-4f12-4d52-a470-e12b048e7ab9" start_index="0" end="d5e3da1d-e5da-4aeb-a9b0-13ea42662515" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0e67a3ec-4f12-4d52-a470-e12b048e7ab9" start_index="0" end="126ac364-e0c5-4657-a165-212e5b7e4ab9" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3b313f48-7bde-4568-9e41-f2608b2128b9" start_index="0" end="0e67a3ec-4f12-4d52-a470-e12b048e7ab9" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d5e3da1d-e5da-4aeb-a9b0-13ea42662515" start_index="0" end="c04241fd-0d2e-4d61-85c9-a426e5d1c012" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="126ac364-e0c5-4657-a165-212e5b7e4ab9" start_index="0" end="c04241fd-0d2e-4d61-85c9-a426e5d1c012" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c04241fd-0d2e-4d61-85c9-a426e5d1c012" start_index="0" end="39b5c3b3-53a3-4c3d-8bd4-30afe68f9869" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="39b5c3b3-53a3-4c3d-8bd4-30afe68f9869" start_index="0" end="04a87303-3483-492c-bac1-288a44c7a0a5" end_index="4" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4e439874-42ab-4efc-abdc-8c7293410eeb" start_index="0" end="04a87303-3483-492c-bac1-288a44c7a0a5" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="00075c90-1128-4aa8-8c87-26153ad148a2" start_index="0" end="04a87303-3483-492c-bac1-288a44c7a0a5" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="895bdde7-9fea-45f6-8f13-9003d75935e3" start_index="0" end="04a87303-3483-492c-bac1-288a44c7a0a5" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="895bdde7-9fea-45f6-8f13-9003d75935e3" start_index="0" end="04a87303-3483-492c-bac1-288a44c7a0a5" end_index="3" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Фоновый просмотр" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>